/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppNovaVerificacaoRouteImport } from './routes/app.nova-verificacao'
import { Route as AppMinhaContaRouteImport } from './routes/app.minha-conta'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'

const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaVerificacaoRoute = AppNovaVerificacaoRouteImport.update({
  id: '/nova-verificacao',
  path: '/nova-verificacao',
  getParentRoute: () => AppRoute,
} as any)
const AppMinhaContaRoute = AppMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastrar': typeof CadastrarRoute
  '/login': typeof LoginRoute
  '/recursos': typeof RecursosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/minha-conta': typeof AppMinhaContaRoute
  '/app/nova-verificacao': typeof AppNovaVerificacaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastrar': typeof CadastrarRoute
  '/login': typeof LoginRoute
  '/recursos': typeof RecursosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/minha-conta': typeof AppMinhaContaRoute
  '/app/nova-verificacao': typeof AppNovaVerificacaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastrar': typeof CadastrarRoute
  '/login': typeof LoginRoute
  '/recursos': typeof RecursosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/minha-conta': typeof AppMinhaContaRoute
  '/app/nova-verificacao': typeof AppNovaVerificacaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastrar'
    | '/login'
    | '/recursos'
    | '/app/configuracoes'
    | '/app/minha-conta'
    | '/app/nova-verificacao'
    | '/app/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/cadastrar'
    | '/login'
    | '/recursos'
    | '/app/configuracoes'
    | '/app/minha-conta'
    | '/app/nova-verificacao'
    | '/app/relatorios'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastrar'
    | '/login'
    | '/recursos'
    | '/app/configuracoes'
    | '/app/minha-conta'
    | '/app/nova-verificacao'
    | '/app/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastrarRoute: typeof CadastrarRoute
  LoginRoute: typeof LoginRoute
  RecursosRoute: typeof RecursosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova-verificacao': {
      id: '/app/nova-verificacao'
      path: '/nova-verificacao'
      fullPath: '/app/nova-verificacao'
      preLoaderRoute: typeof AppNovaVerificacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/minha-conta': {
      id: '/app/minha-conta'
      path: '/minha-conta'
      fullPath: '/app/minha-conta'
      preLoaderRoute: typeof AppMinhaContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppMinhaContaRoute: typeof AppMinhaContaRoute
  AppNovaVerificacaoRoute: typeof AppNovaVerificacaoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppMinhaContaRoute: AppMinhaContaRoute,
  AppNovaVerificacaoRoute: AppNovaVerificacaoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastrarRoute: CadastrarRoute,
  LoginRoute: LoginRoute,
  RecursosRoute: RecursosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
